### ISSUE TITLE
How do you use the GUI interface on Windows 10?

### ISSUE THREAD

**Issue by jaycecd** [Sidneys1/BatchImageProcessor#7]
I've taken a look at the author's work and read the introduction file in the repository, which seems very powerful. 

However, I'm having trouble running the GUI interface on Windows 10!

I directly downloaded the release file `BatchImageProcessor-v2.0.0-win-x64.zip`, unzipped it, and double-clicked the `BatchImageProcessor.exe` file in the folder:

![image](https://github.com/Sidneys1/BatchImageProcessor/assets/33342388/eff21b7f-11b1-4a4c-a4f8-593bbc29d788)

but nothing showed up. 

What's the problem?

**Comment by Sidneys1** [comment]
I'm digging into this, but on a clean install of Windows 10 22H2, double-clicking the EXE opens a dialog stating that I need to install the .NET 6.0 Desktop Runtime:

![image](https://github.com/user-attachments/assets/dbb0fb45-2265-444e-8656-e1ddc44f6ef1)

Clicking <kbd>Yes</kbd> takes me to [the appropriate download site](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.32-windows-x64-installer).

Once installing the runtime, double-clicking the binary launches the application as expected.

So, if this isn't happening for you, please add a comment describing your:
* Windows 10 version (Settings > System > About > "Windows specifications" > "Version" and "OS build")
* Architecture (Settings > System > About > "Device specifications" > "System type")

**Comment by jaycecd** [comment]
Hi, the dialog you mentioned didn't pop up, and I still can't run the program. Here's the information about my computer:

1. Windows 10 version (Settings > System > About > "Windows specifications" > "Version" and "OS build":

    Version: Windows 10 Pro for Workstations
    Version Number: 22H2
    Installation Date: Friday, March 18, 2022
    Operating System Internal Version: 19045.4651
    Experience: Windows Feature Experience Pack 1000.19060.1000.0
    

1. Architecture (Settings > System > About > "Device specifications" > "System type"):

    64-bit operating system, based on x64 processor

**Comment by Sidneys1** [comment]
Retrying with Windows 10 Pro for Workstations, but I can't find anything about this version of Windows behaving differently.

In the meantime, have you tried installing the "[.NET Desktop Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.32-windows-x64-installer)" manually?

**Comment by jaycecd** [comment]
I'm certain that my system has installed the `.NET Desktop Runtime`, which can be seen in the Control Panel:
![image](https://github.com/user-attachments/assets/e91dfa0f-fa10-4d9a-bbfb-e42d381a4797)

Furthermore, I ran `BatchImageProcessor.exe` through CMD without encountering any errors, but I didn't see any program interface appear:
![image](https://github.com/user-attachments/assets/ad916358-c9b3-49a4-bb11-4b2690c80994)

Is there something wrong with the way I'm using it?

**Comment by jaycecd** [comment]
I want to know if `BatchImageProcessor.exe` will pop up a new interface or add buttons to the existing file manager.

**Comment by Sidneys1** [comment]
It will open a new interface, as seen in [the screenshot on the README](https://github.com/Sidneys1/BatchImageProcessor?tab=readme-ov-file#batch-image-processor).

- I've created a self-contained build that shouldn't need the Windows Desktop Runtime, can you try running this?

  [BatchImageProcessor-v2.0.0-win-x64-selfcontained.zip](https://github.com/Sidneys1/BatchImageProcessor/releases/download/v2.0.0/BatchImageProcessor-v2.0.0-win-x64-selfcontained.zip)
- Also, does `bipcli.exe --help` run and output help content?

**Comment by jaycecd** [comment]
I've downloaded the [BatchImageProcessor-v2.0.0-win-x64-selfcontained.zip](https://github.com/Sidneys1/BatchImageProcessor/releases/download/v2.0.0/BatchImageProcessor-v2.0.0-win-x64-selfcontained.zip) and run it, which is the same as the previous [BatchImageProcessor-v2.0.0-win-x64.zip](https://github.com/Sidneys1/BatchImageProcessor/releases/download/v2.0.0/BatchImageProcessor-v2.0.0-win-x64.zip), but it still can't run. However, both programs can get the correct help information by running `bipcli.exe --help`:
![image](https://github.com/user-attachments/assets/5e4781af-4649-4e32-947f-4b23134f0a89)


I've already turned off the antivirus software on my computer, but the program still won't run. I've also tried running it on my other Windows 10 Pro laptop, and the issue persists. If the program has a log, it might be possible to figure out where it's going wrong.

**Comment by Sidneys1** [comment]
I'm at a loss then - the self-contained binary should work. Best I can think is reboot your computer? I'm entirely unable to reproduce this issue, unfortunately.

You can also see the [Microsoft documentation for troubleshooting app launch failures](https://learn.microsoft.com/en-us/dotnet/core/runtime-discovery/troubleshoot-app-launch?pivots=os-windows), although I don't see an item applicable to your situation.

**Comment by jaycecd** [comment]
I've restarted on two computers many times already, but it still won't run.

It's disappointing that I can't use your software, but thank you very much for your help~

**Comment by Sidneys1** [comment]
As a last attempt, I've updated the program from .NET 6 to 8. See if this works:
[BatchImageProcessor-v2.0.1-win-x64.zip](https://github.com/user-attachments/files/16253102/BatchImageProcessor-v2.0.1-win-x64.zip)

**Comment by jaycecd** [comment]
I downloaded the latest software package, but unfortunately, it still wouldn't run. Additionally, when I tried running it on a new Windows 11 Pro computer, it remained unresponsive.
